/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "tertiary": "#a4c9ff",
        "inverse-surface": "#dce1fb",
        "surface-container": "#191f31",
        "on-primary": "#002e6a",
        "tertiary-fixed-dim": "#a4c9ff",
        "secondary": "#bcc7de",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3e495d",
        "background": "#0c1324",
        "on-tertiary-container": "#002a51",
        "surface-tint": "#adc6ff",
        "surface-variant": "#2e3447",
        "on-background": "#dce1fb",
        "on-primary-fixed": "#001a42",
        "on-surface-variant": "#c2c6d6",
        "on-surface": "#dce1fb",
        "on-primary-fixed-variant": "#004395",
        "primary-container": "#4d8eff",
        "surface-container-lowest": "#070d1f",
        "on-secondary-container": "#aeb9d0",
        "on-primary-container": "#00285d",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed": "#d8e3fb",
        "surface-container-low": "#151b2d",
        "surface-dim": "#0c1324",
        "surface-bright": "#33394c",
        "on-secondary-fixed": "#111c2d",
        "surface-container-high": "#23293c",
        "tertiary-container": "#4c93e7",
        "on-tertiary": "#00315d",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#001c39",
        "error": "#ffb4ab",
        "on-secondary": "#263143",
        "surface": "#0c1324",
        "secondary-fixed-dim": "#bcc7de",
        "inverse-primary": "#005ac2",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004883",
        "outline-variant": "#424754",
        "surface-container-highest": "#2e3447",
        "inverse-on-surface": "#2a3043",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        accent: ["Playfair Display", "serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
